apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapa
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: rapa
        image: brian24/rapa:green
        ports:
        - containerPort: 80
